apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcjwl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcjwl
  template:
    metadata:
      labels:
        app: kcjwl
    spec:
      containers:
      - image: okteto.dev/kcjwl:latest
        name: kcjwl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ec41bb12-557f-1e0c-fc5e-704a394f9557"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "ec41bb12-557f-1e0c-fc5e-704a394f9557"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
